### ISSUE TITLE
Service: Php Fastcgi

### ISSUE THREAD

**Issue by simbora** [simbora/infra#14]
Depends on [Php](12) and [Fastcgi](13).

Create `/etc/init/php-fastcgi.conf` with:

```
description "PHP Fastcgi daemon"


start on (local-filesystems and net-device-up)
stop on runlevel [!2345]

respawn

exec /usr/bin/spawn-fcgi \
    -n \
    -a 127.0.0.1 \
    -p 9000 \
    -C 6 \
    -u deploy \
    -g deploy \
    -f /usr/bin/php5-cgi
```

Run:

```
start php-fastcgi
```

**Comment by rxaviers** [comment]
I've updated the description with:

Create `/etc/init/php-fastcgi.conf` with:

    description "PHP Fastcgi daemon"


    start on (local-filesystems and net-device-up)
    stop on runlevel [!2345]

    respawn

    exec /usr/bin/spawn-fcgi \
        -n \
        -a 127.0.0.1 \
        -p 9000 \
        -C 6 \
        -u deploy \
        -g deploy \
        -f /usr/bin/php5-cgi

The previous `expect daemon` way was wrong (start/stop was getting locked).
